version: '3'
services:
    mysql:
      build: ./mysql
      restart: always
      container_name: db
      platform: linux/x86_64
      environment:
          MYSQL_DATABASE: django_db
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: django
          MYSQL_PASSWORD: password
      volumes:
        - tmp:/var/run/mysqld
        - mysql_db_data:/var/lib/mysql
        - ./mysql/db/my.cnf:/etc/mysql/conf.d/my.cnf
        - ./mysql/db/sql:/docker-entrypoint-initdb.d
      ports:
        - 3306:3306
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci 
    python:
      container_name: django
      build: ./python
      volumes:
         - ../:/usr/src/app
         - tmp:/run/mysqld
      restart: always
      ports:
         - 8000:8000
      tty: true
      stdin_open: true
      command: sleep infinity
volumes:
    mysql_db_data:
      driver: local
    tmp:
      driver: local